export const RESET_STATE = 'RESET_STATE';

export const AUTH = {
  LOAD_USER_AUTH: 'LOAD_USER_AUTH',
  REMOVE_USER_AUTH: 'REMOVE_USER_AUTH',
  RESET_STATE: RESET_STATE,
};

export const USER_STORE = {
  UPDATE_LOADING: 'UPDATE_LOADING',
  LOAD_USER_STORE_DATA: 'LOAD_USER_STORE_DATA',
  SET_ERROR: 'SET_ERROR',
  SET_FILTER_OPTIONS: 'SET_FILTER_OPTIONS',
  SET_FILTERED_STORE: 'SET_FILTERED_STORE',
  UPDATE_CURRENT_FILTER: 'UPDATE_CURRENT_FILTER',
  UPDATE_PENDING_IMAGES: 'UPDATE_PENDING_IMAGES',
  RESET_STATE: RESET_STATE,
};
