export const RESET_STATE = 'RESET_STATE';

export const AUTH = {
  LOAD_USER_AUTH: 'LOAD_USER_AUTH',
  REMOVE_USER_AUTH: 'REMOVE_USER_AUTH',
  RESET_STATE: RESET_STATE,
};

export const USER_STORE = {
  UPDATE_LOADING: 'UPDATE_LOADING',
  LOAD_USER_STORE_DATA: 'LOAD_USER_STORE_DATA',
  SET_ERROR: 'SET_ERROR',
  RESET_STATE: RESET_STATE,
};
