const CONTANTS = {
  SCREENS: {
    LOGIN: 'Login',
    HOME: 'Home',
  },
  ASYNC_STORAGE_KEYS: {
    PENDING_IMAGES: 'PENDING_IMAGES',
    LAST_LOGGED_IN_UID: 'LAST_LOGGED_IN_UID',
  },
  MIN_LENGTH: {
    USER_NAME: 5,
    PASSWORD: 5,
  },
  DELAY_LOADING_TIME: 5000,
};

module.exports = CONTANTS;
